apiVersion: apps/v1
kind: Deployment
metadata:
  name: appflowy-redis
spec:
  selector:
    matchLabels:
      app: appflowy-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: appflowy-redis
    spec:
      containers:
        - name: redis
          image: redis:7.2-alpine
          args:
            - --save
            - ""
            - --appendonly
            - "no"
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 5
            periodSeconds: 10
