apiVersion: v1
kind: Service
metadata:
  name: longhorn-ingress-lb
  namespace: longhorn-system
spec:
  selector:
    app: longhorn-ui
  type: LoadBalancer
  loadBalancerIP: 1.1.1.1 # put some value
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http