apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: k8s-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.74-192.168.1.98
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - k8s-pool
