apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-verify
  namespace: metallb-system
  labels:
    app: kube-verify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-verify
  template:
    metadata:
      labels:
        app: kube-verify
    spec:
      containers:
        - name: nginx
          image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: kube-verify
  namespace: metallb-system
spec:
  selector:
    app: kube-verify
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: xxx.xxx.x.xx
