---
# DNS2: 1.0.0.1
persistentVolumeClaim:
  enabled: true
ingress:
  enabled: true
  ingressClass:
  hosts:
    - "pihole.home"
serviceWeb:
  loadBalancerIP: <IP HERE>
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
serviceDns:
  loadBalancerIP: <IP HERE>
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
replicaCount: 1
