# template: https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
global:
  storageClass: longhorn
  postgresql:
    auth:
      existingSecret: postgres-secret
      secretKeys:
        adminPasswordKey: POSTGRES_PASSWORD
