apiVersion: apps/v1
kind: Deployment
metadata:
  name: appflowy-gotrue
spec:
  template:
    spec:
      containers:
        - name: gotrue
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
