apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-verify
  namespace: metallb-system
  labels:
    app: kube-verify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-verify
  template:
    metadata:
      labels:
        app: kube-verify
    spec:
      containers:
        - name: nginx
          image: quay.io/clcollins/kube-verify:01
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kube-verify
  namespace: metallb-system
spec:
  selector:
    app: kube-verify
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
