apiVersion: v1
kind: ConfigMap
metadata:
  name: node-exporter-textfile-collector
  namespace: monitoring
data:
  temperature.sh: |
    #!/bin/bash
    echo "# HELP pi_cpu_temperature Current temperature of the CPU"
    echo "# TYPE pi_cpu_temperature gauge"
    echo "pi_cpu_temperature $(vcgencmd measure_temp | sed -n "s/temp=\([0-9.]*\).*/\1/p")"
